import {API_BASE} from './account.js?v=20261002-shared';
import {ManagerAccount} from './manager-account.js?v=20261002-password';
import {imageFor} from './menu-data.js';
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>new Intl.NumberFormat('ru-RU').format(v||0)+' ₽';
const date=v=>v?new Date(v).toLocaleString('ru-RU',{timeZone:'Europe/Moscow'}):'—';
const account=new ManagerAccount();
let data=null,view='overview',editing=null,refreshing=false;
const titles={overview:'Обзор',products:'Меню и товары',orders:'Заказы',customers:'Клиенты CRM',carts:'Корзины',analytics:'Аналитика',integrations:'Касса и рассылки'};
const status={active:'В продаже',out:'Нет в наличии',draft:'Черновик',archived:'Архив'};
function message(text){$('#message').textContent=text;setTimeout(()=>$('#message').textContent='',6000);}
function photo(p){
  if(p.image_url?.startsWith(`${API_BASE}/catalog/images/`))return `<span class="photo" style="background-image:url('${esc(p.image_url)}');background-size:cover;background-position:center"></span>`;
  const [name,cols,rows,pos]=imageFor(p.image);
  const image=new URL(`./menu-assets/${name}.webp`,import.meta.url).href;
  return `<span class="photo" style="background-image:url('${esc(image)}');background-size:${cols*100}% ${rows*100}%;background-position:${cols===1?0:pos%cols*100/(cols-1)}% ${rows===1?0:Math.floor(pos/cols)*100/(rows-1)}%"></span>`;
}
function table(headers,rows){return rows.length?`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`:'<div class="empty">Пока нет данных</div>';}
function orderRows(orders){return orders.map(o=>`<tr><td>${esc(o.id.slice(0,8).toUpperCase())}<small>${date(o.created_at)}</small></td><td>${esc(o.name)}<small>${o.source==='telegram'?'Telegram':o.source==='site'?'Сайт':'До подключения'}</small></td><td>${o.items.map(i=>`${esc(i.name)} × ${i.count}${i.options?.length?`<small>${i.options.map(esc).join(', ')}</small>`:''}`).join('<br>')}</td><td>${money(o.total)}</td><td><span class="badge">Демо · не оплачен</span></td></tr>`);}
function render(){
  if(!data)return;
  $('#title').textContent=titles[view];
  document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('selected',b.dataset.view===view));
  const s=data.stats;let html='';
  if(view==='overview')html=`<div class="cards">${[['Клиенты',s.customers,'Общие аккаунты сайта и Mini App'],['Контакты бота',s.bot_contacts,'Учёт новых обращений с момента подключения'],['Демо-заказы сегодня',s.demo_orders_today,'За сутки по московскому времени'],['Реальная выручка',money(s.revenue),'Касса ещё не подключена'],['Демо-заказы всего',s.demo_orders,'Это не реальные продажи'],['Сумма демо-заказов',money(s.demo_total),'Без списания денег'],['Брошенные корзины',s.abandoned_carts,'Без изменений больше 30 минут'],['Товары в продаже',data.products.filter(p=>p.product.status==='active').length,'Общий каталог']].map(([label,value,note])=>`<div class="card">${label}<strong>${value}</strong><small>${note}</small></div>`).join('')}</div><div class="spark">Изменения меню сохраняются в общей базе и появляются при следующей загрузке меню. Заказы, корзины и аккаунты сайта и Telegram учитываются вместе.</div><h2 style="margin-top:28px">Последние демо-заказы</h2>${table(['Заказ','Клиент / канал','Состав','Сумма','Статус'],orderRows(data.orders.slice(0,8)))}`;
  if(view==='products')html=`<div class="toolbar"><input type="search" id="filter" placeholder="Поиск по меню"><button class="primary" id="add-product">Добавить товар</button></div><div id="table-area"></div>`;
  if(view==='orders')html=`<p class="muted">Показаны последние ${data.orders.length} заказов, максимум ${data.limits.orders}. Все существующие заказы — демо.</p>${table(['Заказ','Клиент / канал','Состав','Сумма','Статус'],orderRows(data.orders))}`;
  if(view==='customers')html=`<div class="toolbar"><input type="search" id="filter" placeholder="Имя или Telegram"></div><p class="muted">Показаны последние ${data.customers.length} аккаунтов, максимум ${data.limits.customers}.</p><div id="table-area"></div>`;
  if(view==='carts')html=`<p class="muted">Только сохранённые корзины вошедших клиентов. Гостевые корзины нельзя привязать к Telegram. После демо-заказа корзина очищается.</p>${table(['Клиент','Товары','Сумма','Активность','Состояние'],data.carts.map(c=>`<tr><td><button data-customer="${c.user_id}">${esc(c.name)}</button></td><td>${c.items.map(i=>`${esc(i.name)} × ${i.count}`).join('<br>')}</td><td>${money(c.total)}</td><td>${date(c.updated_at)}<small>${c.source==='telegram'?'Telegram':'Сайт'}</small></td><td><span class="badge">${c.abandoned?'Брошена · >30 мин':'Активная'}</span></td></tr>`))}`;
  if(view==='analytics'){
    const ranked=data.products.map(({product:p})=>({p,...(data.analytics.find(a=>a.product_id===p.id)||{units:0,orders:0,demo_total:0})})).sort((a,b)=>b.units-a.units);
    html=`<h2>Популярность в демо-заказах</h2><p class="muted">По всем сохранённым демо-заказам. Это проверка спроса в тестовом режиме, не статистика оплаченных продаж. Позиции с нулём не означают «плохо продаются».</p>${table(['Позиция','Заказов','Количество','Демо-сумма'],ranked.map(a=>`<tr><td>${esc(a.p.name)}<small>${esc(a.p.category)}</small></td><td>${a.orders}</td><td>${a.units} шт.</td><td>${money(a.demo_total)}</td></tr>`))}`;
  }
  if(view==='integrations')html=`<h2>Что подключено</h2><ul><li>Общий каталог: сайт, Mini App, админка.</li><li>Telegram-вход и единая карточка клиента.</li><li>История демо-заказов и синхронизация корзин.</li><li>Игровые скидки — из существующей базы.</li></ul><h2 style="margin-top:24px">Что ещё нужно подключить</h2><ul><li>FreeKassa: реквизиты магазина и серверная проверка платежей. Сейчас платежи не принимаются.</li><li>Работа кухни: приём реальных заказов, статусы готовности и уведомления клиенту.</li><li>Рассылки: отдельный согласованный запуск по доступным контактам бота. Сейчас отправка отключена.</li><li>Склад: остатки, списания и себестоимость. Статус «Нет в наличии» доступен сейчас, количественный склад ещё нет.</li></ul>`;
  $('#content').innerHTML=html;
  if(view==='products'||view==='customers'){renderFiltered();$('#filter').addEventListener('input',renderFiltered);}
  $('#add-product')?.addEventListener('click',()=>editProduct(null));
}
function renderFiltered(){const q=($('#filter')?.value||'').toLocaleLowerCase('ru-RU');
  if(view==='products')$('#table-area').innerHTML=table(['Товар','Категория','Цена','Статус',''],data.products.filter(({product:p})=>`${p.name} ${p.category}`.toLowerCase().includes(q)).map(({product:p})=>`<tr><td><div class="product-cell">${photo(p)}<div>${esc(p.name)}<small>${esc(p.weight)}</small></div></div></td><td>${esc(p.category==='На булке'?'Бургеры':p.category)}</td><td>${money(p.price)}</td><td><span class="badge">${status[p.status]}</span></td><td><button data-edit="${p.id}">Изменить</button></td></tr>`));
  if(view==='customers')$('#table-area').innerHTML=table(['Клиент','Telegram','Демо-заказы','Демо-сумма','Скидки'],data.customers.filter(c=>`${c.name} ${c.username||''} ${c.tg_id}`.toLowerCase().includes(q)).map(c=>`<tr><td><button data-customer="${c.id}">${esc(c.name)}</button><small>${date(c.created_at)}</small></td><td>${c.username?'@'+esc(c.username):esc(c.tg_id)}<small>${c.bot_contact?'Есть контакт с ботом':'Только аккаунт'}</small></td><td>${c.demo_order_count}</td><td>${money(c.demo_order_total)}</td><td>${money(c.discount_balance)}</td></tr>`));
}
async function refresh(){if(refreshing)return;refreshing=true;$('#refresh').disabled=true;const requestToken=account.token;
  try{if(account.me?.must_change_password){showPasswordChange();return;}const snapshot=await account.request('/manage/snapshot');if(account.token!==requestToken)return;data=snapshot;$('#login').hidden=true;$('#password-change').hidden=true;$('#content').hidden=false;$('#identity').textContent=account.me?.name||'Владелец';$('#logout').hidden=false;$('#change-password').hidden=false;render();$('#sync-status').textContent=`Общая база · обновлено ${date(data.generated_at)}`;}
  catch(e){showLogin();$('#login-error').textContent=e.message;}
  finally{refreshing=false;$('#refresh').disabled=false;}
}
function showLogin(){data=null;$('#login').hidden=false;$('#password-change').hidden=true;$('#content').hidden=true;$('#identity').textContent='Нет входа';$('#logout').hidden=!account.token;$('#change-password').hidden=true;$('#sync-status').textContent='';$('#editor').close();$('#customer').close();$('#customer-content').textContent='';$('#product-form').reset();}
function showPasswordChange(){data=null;$('#content').hidden=true;$('#login').hidden=true;$('#password-change').hidden=false;$('#identity').textContent=account.me?.name||'Владелец';$('#logout').hidden=false;$('#change-password').hidden=true;$('#password-cancel').hidden=!!account.me?.must_change_password;$('#password-note').textContent=account.me?.must_change_password?'Первый вход: замените временный пароль своим. После этого откроется админка.':'После смены пароля другие сеансы будут завершены.';$('#sync-status').textContent='';}
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.target,button=f.querySelector('[type=submit]');button.disabled=true;$('#login-error').textContent='';try{await account.login(f.elements.username.value.trim(),f.elements.password.value);f.elements.password.value='';if(account.me.must_change_password)showPasswordChange();else await refresh();}catch(e){$('#login-error').textContent=e.message;}finally{button.disabled=false;}});
$('#password-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.target,button=f.querySelector('[type=submit]');$('#password-error').textContent='';if(f.elements.new_password.value!==f.elements.confirm_password.value){$('#password-error').textContent='Новые пароли не совпадают.';return;}button.disabled=true;try{await account.changePassword(f.elements.current_password.value,f.elements.new_password.value);f.reset();await refresh();message('Пароль изменён. Другие сеансы завершены.');}catch(e){$('#password-error').textContent=e.message;}finally{button.disabled=false;}});
function editProduct(id){editing=id?data.products.find(p=>p.product.id===id):null;const p=editing?.product||{name:'',category:'Шаверма',price:0,weight:'',status:'draft',description:'',image:0,option_groups:[],variants:[]};const f=$('#product-form');for(const key of ['name','category','price','weight','status','description'])f.elements[key].value=p[key];for(const key of ['option_groups','variants'])f.elements[key].value=JSON.stringify(p[key],null,2);f.elements.photo.value='';$('#archive').hidden=!id;$('#editor-error').textContent='';$('#editor').showModal();}
function fileData(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(new Error('Не удалось прочитать фото'));r.readAsDataURL(file);});}
$('#product-form').addEventListener('submit',async event=>{event.preventDefault();const f=event.target;const submit=f.querySelector('[type=submit]');submit.disabled=true;
  try{const file=f.elements.photo.files[0];if(file&&(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>1000000))throw new Error('Фото: PNG, JPEG или WebP до 1 МБ');const p={...(editing?.product||{image:0})};for(const key of ['name','category','weight','status','description'])p[key]=f.elements[key].value.trim();p.price=Number(f.elements.price.value);p.option_groups=JSON.parse(f.elements.option_groups.value);p.variants=JSON.parse(f.elements.variants.value);let saved=await account.request('/manage/products','POST',{id:editing?.product.id||null,version:editing?.version||null,product:p});editing=saved;if(file)await account.request(`/manage/products/${saved.product.id}/image`,'POST',{version:saved.version,image_data:await fileData(file)});$('#editor').close();await refresh();message('Товар сохранён в общей базе меню');}
  catch(e){$('#editor-error').textContent=e.message;}finally{submit.disabled=false;}
});
$('#archive').addEventListener('click',()=>{if(!confirm('Убрать товар из меню? Он останется в архиве и старых заказах.'))return;$('#product-form').elements.status.value='archived';$('#product-form').requestSubmit();});
function showCustomer(id){const c=data.customers.find(c=>c.id===id);if(!c){message('Клиент не входит в текущие 1000 карточек');return;}const orders=data.orders.filter(o=>o.user_id===id);const cart=data.carts.find(c=>c.user_id===id);$('#customer-content').innerHTML=`<h2>${esc(c.name)}</h2><p>${c.username?'@'+esc(c.username):'Без username'} · Telegram ID ${esc(c.tg_id)}</p><p class="muted">Первое обращение: ${date(c.created_at)}<br>Последняя активность аккаунта: ${date(c.updated_at)}</p><div class="cards"><div class="card">Демо-заказы<strong>${c.demo_order_count}</strong></div><div class="card">Демо-сумма<strong>${money(c.demo_order_total)}</strong></div><div class="card">Скидка<strong>${money(c.discount_balance)}</strong></div></div><div class="profile-history"><h2>Текущая корзина</h2>${cart?cart.items.map(i=>`<p>${esc(i.name)} × ${i.count}</p>`).join(''):'Корзина пуста'}<h2 style="margin-top:25px">История демо-заказов</h2><p class="muted">Из последних 500 заказов системы.</p>${table(['Заказ','Клиент / канал','Состав','Сумма','Статус'],orderRows(orders))}</div>`;$('#customer').showModal();}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view){view=b.dataset.view;render();}if(b.dataset.edit)editProduct(Number(b.dataset.edit));if(b.dataset.customer)showCustomer(Number(b.dataset.customer));if(b.hasAttribute('data-close'))b.closest('dialog').close();});
$('#refresh').addEventListener('click',refresh);
$('#change-password').addEventListener('click',showPasswordChange);
$('#password-cancel').addEventListener('click',()=>{$('#password-form').reset();void refresh();});
$('#logout').addEventListener('click',async()=>{try{await account.logout();$('#password-form').reset();$('#login-form').reset();showLogin();$('#login-error').textContent='';}catch(e){message(e.message);}});
window.addEventListener('focus',()=>{if(account.token&&$('#password-change').hidden)void refresh();});
try{await account.connect();if(account.token)await refresh();}catch(e){showLogin();$('#login-error').textContent=e.message;}
setInterval(()=>{if(account.token&&!document.hidden&&!$('#editor').open&&$('#password-change').hidden)void refresh();},30000);
